### ISSUE TITLE
Support for dynamic nested, hydratable components?

### ISSUE THREAD

**Issue by bent** [estrattonbailey/react-hydrate#1]
Does this support nested, hydratable components, where the nesting is dynamic? For example:

1. You have a top-level component that has a dataLoader function and thus loads data asynchronously. However, whilst that asychronous activity is taking place, it renders some sort of activity indicator.
2. When the asynchronous activity finishes, the activity indicator is replaced with another component. However, that component _also_ has its own dataLoader function, which kicks off its own asynchronous data load.

Put differently, imagine that in the example you have in your README, both the Projects _and_ the Project component are wrapped with `hydrate` and have a dataLoader function. On the server side, I need to wait for _all_ of this asynchronous activity to finish before I can send a response back to the client. Does react-hydrate support this scenario?

**Comment by estrattonbailey** [comment]
Hey @bent! Yes, that's the idea. Nested components still "render", the user is just responsible for handling the `loading` state. So whatever dataLoaders you define via `hydrate` are still found, however deep in the tree they are. On the server, they start loading as soon as they're evaluated, and then running `store.fetch()` on the server just ensures they're all finished loading before sending a rendered response to the client.

Still working on a v1, so things might change. Would love to hear any feedback you have!
